#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=28
#SBATCH --mem=60G
#SBATCH --job-name=orthf_g_akker_fasttree
#SBATCH --output=orthf_g_akker_fasttree.out
#SBATCH --error=orthf_g_akker_fasttree.err


source ~/.bashrc
conda deactivate
export PATH="/data_1/jmaturana/Software/OrthoFinder:$PATH"
# export PATH="/home/jmaturana/miniconda3/envs/bif2021.1/bin:$PATH"
# bif2020.1 env doesn't have orthofinder but has scipy/numpy, diamond 2.0.x, fasttre, mafft, mcl, fastme and iqtree
export PATH="/home/jmaturana/miniconda3/envs/bif2020.1/bin:$PATH"
# Trying code from github
echo "which orthofinder $(which orthofinder.py)"
echo "which diamond $(which diamond)"
echo $(diamond version)
iqtree --version

echo `date`
SECONDS=0

# This uses `-b` but with a edited 'SpeciesIDs.txt' file (inside 'WorkingDirectory'),
# where genomes ids were commented out to only use muciniphila (gtdbtk) genomes
root="/home/jmaturana/Akker/OrthoFinder"
faa_to_add="/data_1/jmaturana/Akker/glycaniphila_outgroup_faa"
previous_results='/data_1/jmaturana/Akker/Orthofinder/Results_Jul21'
# if species will be removed, comment them out here
new_species_ids="SpeciesIDs_new_outg.txt" 

out_file="orthf_g_akker_fasttree.out"
job_file="orthofinder_akker_fasttree.job"
output_dir="Results_Aug11"
ncpus=$SLURM_CPUS_PER_TASK

# Moving the default species ids into root, then copying the modiefied ids into 
# WorkingDirectory/
mv ${previous_results}"/WorkingDirectory/SpeciesIDs.txt" ${previous_results}
echo "cp  ${previous_results}/${new_species_ids} ${previous_results}/WorkingDirectory/SpeciesIDs.txt"
cp  ${previous_results}"/${new_species_ids}" ${previous_results}"/WorkingDirectory/SpeciesIDs.txt"

# -a should be 4-8x less than -t because of memory consumption (see github)
# Trying to fix problems. First adding and removing genomes, without using msa. Next step will be -M msa
orthofinder.py -b $previous_results -f $faa_to_add -M msa -t $ncpus -a 8



duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
echo `date`

# Re-establish the original SpeciesIDs.txt
mv ${previous_results}"/SpeciesIDs.txt" ${previous_results}"/WorkingDirectory/"

# Compress the results
cp $job_file $out_file "${root}/${output_dir}"
cd $root
tar --use-compress-program='xz -T 8'  -cf orthofinder_${output_dir}.tar.xz ${output_dir}/Log.txt ${output_dir}/Phylogenetic_Hierarchical_Orthogroups/ ${output_dir}/Species_Tree ${output_dir}/Gene_Trees ${output_dir}/Resolved_Gene_Trees/ ${output_dir}/Comparative_Genomics_Statistics ${output_dir}/Orthogroup_Sequences "${output_dir}/${job_file}" "${output_dir}/${out_file}"
