#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --job-name=hogs_clades
#SBATCH --output=hogs_from_clades.out
#SBATCH --error=hogs_from_clades.err

# set -x 
source /home/jmaturana/.bashrc
conda deactivate
export PATH="/home/jmaturana/miniconda3/envs/bif2021.1/bin:$PATH"


which diamond
diamond version

# root where all the orthofinder result folder(s) are located
root="$HOME/Akker/g_akk_prokka_faa_repr_fast/OrthoFinder"
# Specific results from orthofinder, where all the target files are located
results_dir="${root}/Results_Nov25"
# Nx.tsv files
Ns="${results_dir}/Phylogenetic_Hierarchical_Orthogroups"
# Species tree
tree="${results_dir}/Species_Tree/SpeciesTree_rooted_node_labels.txt"
# The orthofinder source code
py_create="${HOME}/Software/OrthoFinder/tools/create_files_for_hogs.py"
# Script to select the single-copy HOGs
py_single_copy="${HOME}/Software/my_scripts/single_copy_hogs.py"

# Move inside the orthofinder results to place all the output there
cd $results_dir
echo current path: `pwd`
# Select a set of nodes from the species tree
for node in {0..13}; #N25 N24 N40 N9 N8 N27 N8; 
    do
        # Create all the HOGs sequences for each node
        # inside HOGs_seqs will be the seqs, all the dirs will be created
        python $py_create $results_dir HOGs_seqs N$node
        # Select the single-copy HOGs for each node
        python $py_single_copy $Ns N$node "HOGs_seqs/N${node}/HOG_Sequences" $tree
        
        # destination for the single-copy HOGs
        dest="single_copy_HOGs/scogs_N${node}_seqs"
        mkdir -p $dest
        # copy the the single-copy HOGs
        parallel "cp N${node}/HOG_Sequences/{}.fa $dest" \
         :::: single_copy_HOGs_N${node}.list
    done

# Compress the sequences created by $py_create
tar -cf hogs_seqs_nodes.tar.gz HOGs_seqs/N*
# compress the single-copy HOGs
tar -cf single_copy_HOGs.tar.gz single_copy_HOGs/
